// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Auth
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Authentication : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Authentication GetRootAsAuthentication(ByteBuffer _bb) { return GetRootAsAuthentication(_bb, new Authentication()); }
  public static Authentication GetRootAsAuthentication(ByteBuffer _bb, Authentication obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyAuthentication(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, AuthenticationVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Authentication __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string AccessToken { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAccessTokenBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetAccessTokenBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetAccessTokenArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Auth.Authentication> CreateAuthentication(FlatBufferBuilder builder,
      StringOffset access_tokenOffset = default(StringOffset)) {
    builder.StartTable(1);
    Authentication.AddAccessToken(builder, access_tokenOffset);
    return Authentication.EndAuthentication(builder);
  }

  public static void StartAuthentication(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddAccessToken(FlatBufferBuilder builder, StringOffset accessTokenOffset) { builder.AddOffset(0, accessTokenOffset.Value, 0); }
  public static Offset<Auth.Authentication> EndAuthentication(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Auth.Authentication>(o);
  }
  public static void FinishAuthenticationBuffer(FlatBufferBuilder builder, Offset<Auth.Authentication> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedAuthenticationBuffer(FlatBufferBuilder builder, Offset<Auth.Authentication> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class AuthenticationVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*AccessToken*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
