// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Cellverse
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CellSpawn : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CellSpawn GetRootAsCellSpawn(ByteBuffer _bb) { return GetRootAsCellSpawn(_bb, new CellSpawn()); }
  public static CellSpawn GetRootAsCellSpawn(ByteBuffer _bb, CellSpawn obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyCellSpawn(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, CellSpawnVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CellSpawn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float X { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int Size { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<Cellverse.CellSpawn> CreateCellSpawn(FlatBufferBuilder builder,
      int id = 0,
      float x = 0.0f,
      float y = 0.0f,
      int size = 0) {
    builder.StartTable(4);
    CellSpawn.AddSize(builder, size);
    CellSpawn.AddY(builder, y);
    CellSpawn.AddX(builder, x);
    CellSpawn.AddId(builder, id);
    return CellSpawn.EndCellSpawn(builder);
  }

  public static void StartCellSpawn(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(1, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(2, y, 0.0f); }
  public static void AddSize(FlatBufferBuilder builder, int size) { builder.AddInt(3, size, 0); }
  public static Offset<Cellverse.CellSpawn> EndCellSpawn(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Cellverse.CellSpawn>(o);
  }
  public static void FinishCellSpawnBuffer(FlatBufferBuilder builder, Offset<Cellverse.CellSpawn> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedCellSpawnBuffer(FlatBufferBuilder builder, Offset<Cellverse.CellSpawn> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class CellSpawnVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*X*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Y*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Size*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
