// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Echo
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EchoMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EchoMessage GetRootAsEchoMessage(ByteBuffer _bb) { return GetRootAsEchoMessage(_bb, new EchoMessage()); }
  public static EchoMessage GetRootAsEchoMessage(ByteBuffer _bb, EchoMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyEchoMessage(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, EchoMessageVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EchoMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Message { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Echo.EchoMessage> CreateEchoMessage(FlatBufferBuilder builder,
      StringOffset messageOffset = default(StringOffset)) {
    builder.StartTable(1);
    EchoMessage.AddMessage(builder, messageOffset);
    return EchoMessage.EndEchoMessage(builder);
  }

  public static void StartEchoMessage(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(0, messageOffset.Value, 0); }
  public static Offset<Echo.EchoMessage> EndEchoMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Echo.EchoMessage>(o);
  }
  public static void FinishEchoMessageBuffer(FlatBufferBuilder builder, Offset<Echo.EchoMessage> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedEchoMessageBuffer(FlatBufferBuilder builder, Offset<Echo.EchoMessage> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class EchoMessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Message*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
